-- ============================================================
-- File: schema_postgres_step06.sql
-- 用途說明：
--   PVESPS Step_06 機器學習訓練資料集 DDL。
--   1) mart.fact_generation_actual_daily：每日實際或模擬發電量標籤。
--   2) mart.ml_training_generation_daily：模型訓練用每日寬表。
--   3) meta.model_training_dataset_log：訓練資料集建置紀錄。
-- 目標資料庫：PostgreSQL
-- ============================================================

BEGIN;

-- ============================================================
-- 0. 資料結構命名空間
-- ============================================================
-- mart：保存發電量標籤與模型訓練寬表。
CREATE SCHEMA IF NOT EXISTS mart;
-- meta：保存資料集建置紀錄與追蹤資訊。
CREATE SCHEMA IF NOT EXISTS meta;

-- ============================================================
-- 1. mart.fact_generation_actual_daily
--    監督式學習使用的每日發電量標籤資料表。
-- ============================================================
CREATE TABLE IF NOT EXISTS mart.fact_generation_actual_daily (
    fact_id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id                       BIGINT NOT NULL,
    site_sk                      INTEGER NOT NULL,
    location_sk                  INTEGER,
    generation_date              DATE NOT NULL,

    actual_generation_kwh        NUMERIC(12,2) NOT NULL,
    actual_type                  VARCHAR(20) NOT NULL DEFAULT 'simulated',

    weather_adjustment_factor    NUMERIC(8,4),
    efficiency_factor            NUMERIC(8,4),
    maintenance_flag             BOOLEAN NOT NULL DEFAULT FALSE,
    source_note                  VARCHAR(200),

    loaded_at                    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_fgad_actual_generation_kwh
        CHECK (actual_generation_kwh >= 0),

    CONSTRAINT ck_fgad_actual_type
        CHECK (actual_type IN ('actual', 'simulated')),

    CONSTRAINT uq_fgad_site_date_type
        UNIQUE (site_sk, generation_date, actual_type)
);

COMMENT ON TABLE mart.fact_generation_actual_daily IS
'每日實際或模擬發電量標籤表，供機器學習訓練使用。';

COMMENT ON COLUMN mart.fact_generation_actual_daily.actual_type IS
'actual 表示實測發電量，simulated 表示規則或合成標籤。';

COMMENT ON COLUMN mart.fact_generation_actual_daily.weather_adjustment_factor IS
'依天氣條件推導的調整係數，例如雲量或降雨造成的衰減。';

COMMENT ON COLUMN mart.fact_generation_actual_daily.efficiency_factor IS
'估算設備或面板效率係數。';

-- 選用外鍵：確認實際維度表名稱後再啟用。
-- ALTER TABLE mart.fact_generation_actual_daily
--   ADD CONSTRAINT fk_fgad_site
--   FOREIGN KEY (site_sk) REFERENCES dim.solar_site(site_sk);

-- ALTER TABLE mart.fact_generation_actual_daily
--   ADD CONSTRAINT fk_fgad_location
--   FOREIGN KEY (location_sk) REFERENCES dim.location(location_sk);

CREATE INDEX IF NOT EXISTS ix_fgad_generation_date
    ON mart.fact_generation_actual_daily (generation_date);

CREATE INDEX IF NOT EXISTS ix_fgad_site_date
    ON mart.fact_generation_actual_daily (site_sk, generation_date);

CREATE INDEX IF NOT EXISTS ix_fgad_run_id
    ON mart.fact_generation_actual_daily (run_id);

CREATE INDEX IF NOT EXISTS ix_fgad_location_date
    ON mart.fact_generation_actual_daily (location_sk, generation_date);

-- ============================================================
-- 2. mart.ml_training_generation_daily
--    Step_07 模型訓練使用的每日寬表。
-- ============================================================
CREATE TABLE IF NOT EXISTS mart.ml_training_generation_daily (
    row_id                           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id                           BIGINT NOT NULL,
    site_sk                          INTEGER NOT NULL,
    location_sk                      INTEGER,
    training_date                    DATE NOT NULL,

    -- 目標欄位
    target_generation_kwh            NUMERIC(12,2),
    target_available                 BOOLEAN NOT NULL DEFAULT FALSE,
    target_type                      VARCHAR(20) NOT NULL DEFAULT 'simulated',

    -- 日期與日曆特徵
    year_num                         INTEGER,
    month_num                        INTEGER,
    day_num                          INTEGER,
    day_of_year                      INTEGER,
    week_of_year                     INTEGER,
    weekday_num                      INTEGER,
    is_weekend                       BOOLEAN,
    season_code                      VARCHAR(10),

    -- 案場靜態特徵
    install_area_ping                NUMERIC(10,2),
    capacity_kw                      NUMERIC(10,2),
    panel_efficiency                 NUMERIC(8,4),
    site_region                      VARCHAR(30),
    site_county                      VARCHAR(30),
    site_type                        VARCHAR(30),

    -- 天氣與日照特徵
    sunshine_hours                   NUMERIC(8,2),
    sunshine_rate_pct                NUMERIC(8,2),
    solar_radiation_mj_m2            NUMERIC(10,2),
    pop_value                        NUMERIC(8,2),
    pop_type                         VARCHAR(20),
    forecast_issue_time              TIMESTAMP,
    rain_risk_flag                   BOOLEAN,
    cloudy_risk_flag                 BOOLEAN,

    -- 衍生與交互特徵
    estimated_generation_rule_kwh    NUMERIC(12,2),
    generation_per_ping              NUMERIC(10,4),
    sunshine_x_area                  NUMERIC(14,4),
    radiation_x_area                 NUMERIC(14,4),
    pop_x_sunshine                   NUMERIC(14,4),

    -- 落後期與移動平均特徵
    lag_1_generation_kwh             NUMERIC(12,2),
    lag_3_avg_generation_kwh         NUMERIC(12,2),
    lag_7_avg_generation_kwh         NUMERIC(12,2),
    lag_14_avg_generation_kwh        NUMERIC(12,2),

    lag_1_sunshine_hours             NUMERIC(8,2),
    lag_3_avg_sunshine_hours         NUMERIC(8,2),

    -- 資料品質欄位
    feature_missing_cnt              INTEGER NOT NULL DEFAULT 0,
    is_valid_for_training            BOOLEAN NOT NULL DEFAULT TRUE,
    invalid_reason                   VARCHAR(200),

    loaded_at                        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_mltgd_target_type
        CHECK (target_type IN ('actual', 'simulated')),

    CONSTRAINT ck_mltgd_target_generation_kwh
        CHECK (target_generation_kwh IS NULL OR target_generation_kwh >= 0),

    CONSTRAINT ck_mltgd_install_area_ping
        CHECK (install_area_ping IS NULL OR install_area_ping >= 0),

    CONSTRAINT ck_mltgd_capacity_kw
        CHECK (capacity_kw IS NULL OR capacity_kw >= 0),

    CONSTRAINT ck_mltgd_panel_efficiency
        CHECK (panel_efficiency IS NULL OR (panel_efficiency >= 0 AND panel_efficiency <= 1.5)),

    CONSTRAINT ck_mltgd_sunshine_hours
        CHECK (sunshine_hours IS NULL OR sunshine_hours >= 0),

    CONSTRAINT ck_mltgd_sunshine_rate_pct
        CHECK (sunshine_rate_pct IS NULL OR (sunshine_rate_pct >= 0 AND sunshine_rate_pct <= 100)),

    CONSTRAINT ck_mltgd_solar_radiation
        CHECK (solar_radiation_mj_m2 IS NULL OR solar_radiation_mj_m2 >= 0),

    CONSTRAINT ck_mltgd_pop_value
        CHECK (pop_value IS NULL OR (pop_value >= 0 AND pop_value <= 100)),

    CONSTRAINT ck_mltgd_feature_missing_cnt
        CHECK (feature_missing_cnt >= 0),

    CONSTRAINT uq_mltgd_site_date
        UNIQUE (site_sk, training_date)
);

COMMENT ON TABLE mart.ml_training_generation_daily IS
'機器學習可用的每日訓練資料集，每個案場每日一列。';

COMMENT ON COLUMN mart.ml_training_generation_daily.target_generation_kwh IS
'迴歸模型預測目標欄位。';

COMMENT ON COLUMN mart.ml_training_generation_daily.target_available IS
'資料列是否具備可用的模型訓練標籤。';

COMMENT ON COLUMN mart.ml_training_generation_daily.feature_missing_cnt IS
'指定模型特徵欄位的空值或缺失數量。';

COMMENT ON COLUMN mart.ml_training_generation_daily.is_valid_for_training IS
'資料品質檢查後的整體訓練可用旗標。';

-- 選用外鍵：確認實際維度表名稱後再啟用。
-- ALTER TABLE mart.ml_training_generation_daily
--   ADD CONSTRAINT fk_mltgd_site
--   FOREIGN KEY (site_sk) REFERENCES dim.solar_site(site_sk);

-- ALTER TABLE mart.ml_training_generation_daily
--   ADD CONSTRAINT fk_mltgd_location
--   FOREIGN KEY (location_sk) REFERENCES dim.location(location_sk);

CREATE INDEX IF NOT EXISTS ix_mltgd_training_date
    ON mart.ml_training_generation_daily (training_date);

CREATE INDEX IF NOT EXISTS ix_mltgd_site_date
    ON mart.ml_training_generation_daily (site_sk, training_date);

CREATE INDEX IF NOT EXISTS ix_mltgd_run_id
    ON mart.ml_training_generation_daily (run_id);

CREATE INDEX IF NOT EXISTS ix_mltgd_valid_training
    ON mart.ml_training_generation_daily (is_valid_for_training, training_date);

CREATE INDEX IF NOT EXISTS ix_mltgd_target_available
    ON mart.ml_training_generation_daily (target_available, training_date);

CREATE INDEX IF NOT EXISTS ix_mltgd_location_date
    ON mart.ml_training_generation_daily (location_sk, training_date);

-- ============================================================
-- 3. meta.model_training_dataset_log
--    Step_06 資料集建置紀錄，提供輕量 MLOps 追蹤資訊。
-- ============================================================
CREATE TABLE IF NOT EXISTS meta.model_training_dataset_log (
    dataset_run_id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id                        BIGINT NOT NULL,
    dataset_name                  VARCHAR(100) NOT NULL,
    date_from                     DATE NOT NULL,
    date_to                       DATE NOT NULL,

    total_rows                    INTEGER NOT NULL DEFAULT 0,
    valid_rows                    INTEGER NOT NULL DEFAULT 0,
    invalid_rows                  INTEGER NOT NULL DEFAULT 0,
    missing_rate_pct              NUMERIC(8,2),
    target_type                   VARCHAR(20) NOT NULL DEFAULT 'simulated',

    created_at                    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_mtdl_total_rows
        CHECK (total_rows >= 0),

    CONSTRAINT ck_mtdl_valid_rows
        CHECK (valid_rows >= 0),

    CONSTRAINT ck_mtdl_invalid_rows
        CHECK (invalid_rows >= 0),

    CONSTRAINT ck_mtdl_rows_consistency
        CHECK (valid_rows + invalid_rows <= total_rows),

    CONSTRAINT ck_mtdl_missing_rate_pct
        CHECK (missing_rate_pct IS NULL OR (missing_rate_pct >= 0 AND missing_rate_pct <= 100)),

    CONSTRAINT ck_mtdl_target_type
        CHECK (target_type IN ('actual', 'simulated'))
);

COMMENT ON TABLE meta.model_training_dataset_log IS
'每次機器學習訓練資料集建置的紀錄表。';

COMMENT ON COLUMN meta.model_training_dataset_log.dataset_name IS
'通常填入 mart.ml_training_generation_daily。';

CREATE INDEX IF NOT EXISTS ix_mtdl_run_id
    ON meta.model_training_dataset_log (run_id);

CREATE INDEX IF NOT EXISTS ix_mtdl_dataset_name_created_at
    ON meta.model_training_dataset_log (dataset_name, created_at DESC);

CREATE INDEX IF NOT EXISTS ix_mtdl_date_range
    ON meta.model_training_dataset_log (date_from, date_to);

COMMIT;