-- ============================================================
-- File: schema_postgres_step08.sql
-- Purpose:
--   Step_08 batch scoring / prediction result tables for PVESPS
--   1) mart.fact_generation_prediction_daily
--   2) meta.model_scoring_run_log
-- Target DB: PostgreSQL
-- ============================================================

BEGIN;

-- ============================================================
-- 0. Schemas
-- ============================================================
CREATE SCHEMA IF NOT EXISTS mart;
CREATE SCHEMA IF NOT EXISTS meta;

-- ============================================================
-- 1. mart.fact_generation_prediction_daily
--    Daily prediction fact table
-- ============================================================
CREATE TABLE IF NOT EXISTS mart.fact_generation_prediction_daily (
    prediction_id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id                         BIGINT NOT NULL,

    site_sk                        INTEGER NOT NULL,
    location_sk                    INTEGER,
    prediction_date                DATE NOT NULL,

    model_name                     VARCHAR(100) NOT NULL,
    model_version                  VARCHAR(50),
    prediction_type                VARCHAR(20) NOT NULL DEFAULT 'day_ahead',

    predicted_generation_kwh       NUMERIC(12,2) NOT NULL,
    actual_generation_kwh          NUMERIC(12,2),
    prediction_error_kwh           NUMERIC(12,2),
    abs_error_kwh                  NUMERIC(12,2),
    abs_pct_error                  NUMERIC(8,4),

    lower_bound_kwh                NUMERIC(12,2),
    upper_bound_kwh                NUMERIC(12,2),

    is_latest_prediction           BOOLEAN NOT NULL DEFAULT TRUE,
    is_actual_backfilled           BOOLEAN NOT NULL DEFAULT FALSE,

    source_table                   VARCHAR(150),
    source_date_from               DATE,
    source_date_to                 DATE,
    source_row_count               INTEGER,

    created_at                     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_fgpd_predicted_generation_kwh
        CHECK (predicted_generation_kwh >= 0),

    CONSTRAINT ck_fgpd_actual_generation_kwh
        CHECK (actual_generation_kwh IS NULL OR actual_generation_kwh >= 0),

    CONSTRAINT ck_fgpd_prediction_type
        CHECK (prediction_type IN ('day_ahead', 'historical_backtest', 'reforecast')),

    CONSTRAINT ck_fgpd_source_row_count
        CHECK (source_row_count IS NULL OR source_row_count >= 0),

    CONSTRAINT uq_fgpd_site_date_model_version
        UNIQUE (site_sk, prediction_date, model_name, model_version, prediction_type)
);

COMMENT ON TABLE mart.fact_generation_prediction_daily IS
'Daily prediction fact table for site-level generation forecasting.';

COMMENT ON COLUMN mart.fact_generation_prediction_daily.prediction_type IS
'day_ahead = production-like daily scoring; historical_backtest = retrospective scoring; reforecast = rerun / revised prediction';

COMMENT ON COLUMN mart.fact_generation_prediction_daily.is_latest_prediction IS
'Whether this row should be considered the active/latest prediction for the site-date';

COMMENT ON COLUMN mart.fact_generation_prediction_daily.is_actual_backfilled IS
'Whether actual generation has been backfilled for evaluation';

COMMENT ON COLUMN mart.fact_generation_prediction_daily.prediction_error_kwh IS
'actual_generation_kwh - predicted_generation_kwh';

COMMENT ON COLUMN mart.fact_generation_prediction_daily.abs_pct_error IS
'Absolute percentage error, usually abs(actual-predicted)/actual * 100';

-- Optional FK (enable after confirming actual dimension table names)
-- ALTER TABLE mart.fact_generation_prediction_daily
--   ADD CONSTRAINT fk_fgpd_site
--   FOREIGN KEY (site_sk) REFERENCES mart.dim_solar_site(site_sk);

CREATE INDEX IF NOT EXISTS ix_fgpd_prediction_date
    ON mart.fact_generation_prediction_daily (prediction_date);

CREATE INDEX IF NOT EXISTS ix_fgpd_site_date
    ON mart.fact_generation_prediction_daily (site_sk, prediction_date);

CREATE INDEX IF NOT EXISTS ix_fgpd_run_id
    ON mart.fact_generation_prediction_daily (run_id);

CREATE INDEX IF NOT EXISTS ix_fgpd_model_name
    ON mart.fact_generation_prediction_daily (model_name, model_version);

CREATE INDEX IF NOT EXISTS ix_fgpd_latest_prediction
    ON mart.fact_generation_prediction_daily (is_latest_prediction, prediction_date);

CREATE INDEX IF NOT EXISTS ix_fgpd_location_date
    ON mart.fact_generation_prediction_daily (location_sk, prediction_date);

-- ============================================================
-- 2. meta.model_scoring_run_log
--    Scoring run summary log
-- ============================================================
CREATE TABLE IF NOT EXISTS meta.model_scoring_run_log (
    scoring_run_id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id                         BIGINT NOT NULL,

    pipeline_name                  VARCHAR(100) NOT NULL,
    model_name                     VARCHAR(100) NOT NULL,
    model_version                  VARCHAR(50),

    prediction_type                VARCHAR(20) NOT NULL DEFAULT 'day_ahead',
    source_table                   VARCHAR(150) NOT NULL,

    score_date_from                DATE,
    score_date_to                  DATE,

    total_input_rows               INTEGER NOT NULL DEFAULT 0,
    scored_rows                    INTEGER NOT NULL DEFAULT 0,
    output_rows                    INTEGER NOT NULL DEFAULT 0,
    failed_rows                    INTEGER NOT NULL DEFAULT 0,

    status                         VARCHAR(20) NOT NULL DEFAULT 'SUCCESS',
    message                        VARCHAR(1000),

    created_at                     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_msrl_prediction_type
        CHECK (prediction_type IN ('day_ahead', 'historical_backtest', 'reforecast')),

    CONSTRAINT ck_msrl_total_input_rows
        CHECK (total_input_rows >= 0),

    CONSTRAINT ck_msrl_scored_rows
        CHECK (scored_rows >= 0),

    CONSTRAINT ck_msrl_output_rows
        CHECK (output_rows >= 0),

    CONSTRAINT ck_msrl_failed_rows
        CHECK (failed_rows >= 0),

    CONSTRAINT ck_msrl_status
        CHECK (status IN ('SUCCESS', 'FAILED', 'PARTIAL_SUCCESS'))
);

COMMENT ON TABLE meta.model_scoring_run_log IS
'Summary log for model batch scoring runs.';

COMMENT ON COLUMN meta.model_scoring_run_log.run_id IS
'Foreign-style reference to meta.etl_run_log.run_id for the scoring pipeline run';

CREATE INDEX IF NOT EXISTS ix_msrl_run_id
    ON meta.model_scoring_run_log (run_id);

CREATE INDEX IF NOT EXISTS ix_msrl_model_name_created_at
    ON meta.model_scoring_run_log (model_name, model_version, created_at DESC);

CREATE INDEX IF NOT EXISTS ix_msrl_prediction_type
    ON meta.model_scoring_run_log (prediction_type, created_at DESC);

COMMIT;